config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/eosc-perf:
      branch: master
      repo: https://github.com/eosc-synergy/eosc-perf
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/eosc-perf git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-jade-rabbit.sh
        container: qc.acc_grumpy-linen-chipmunk
  QC.Doc:
    repos:
      github.com/eosc-synergy/eosc-perf find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-vermilion-rhinoceros.sh
        container: qc.doc_boozy-goldenrod-moose
      github.com/eosc-synergy/eosc-perf git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-yellow-turkey.sh
        container: qc.doc_frumpy-pink-dunker
      github.com/eosc-synergy/eosc-perf markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-rose-mammoth.sh
        container: qc.doc_ugly-yellow-duck
      github.com/eosc-synergy/eosc-perf restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-gamboge-albatross.sh
        container: qc.doc_shabby-chartreuse-scorpion
  QC.Lic:
    repos:
      github.com/eosc-synergy/eosc-perf licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-magnolia-chinook.sh
        container: qc.lic_crabby-cobalt-leopard
  QC.Met:
    repos:
      github.com/eosc-synergy/eosc-perf validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-apricot-panda.sh
        container: qc.met_tacky-lavender-mastiff
  QC.Sec:
    repos:
      github.com/eosc-synergy/eosc-perf bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-denim-horse.sh
        container: qc.sec_wimpy-wisteria-insect
  QC.Sty:
    repos:
      github.com/eosc-synergy/eosc-perf flake8:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-violet-tortoise.sh
        container: qc.sty_chewy-pink-terrier
      github.com/eosc-synergy/eosc-perf hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-grey-kangaroo.sh
        container: qc.sty_hilly-violet-giraffe
      github.com/eosc-synergy/eosc-perf jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-gamboge-monster.sh
        container: qc.sty_hazy-flax-gar
  QC.Ver:
    repos:
      github.com/eosc-synergy/eosc-perf get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-corn-fly.sh
        container: qc.ver_clammy-grey-fish
timeout: 5400
