config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/eosc-perf:
      branch: master
      repo: https://github.com/eosc-synergy/eosc-perf
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/eosc-perf git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-flax-camel.sh
        container: qc.acc_beady-olive-eagle
  QC.Doc:
    repos:
      github.com/eosc-synergy/eosc-perf find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-pumpkin-kakapo.sh
        container: qc.doc_stuffy-pumpkin-balinese
      github.com/eosc-synergy/eosc-perf git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-peach-shrew.sh
        container: qc.doc_cozy-blue-tapir
      github.com/eosc-synergy/eosc-perf markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-magenta-affenpinscher.sh
        container: qc.doc_scaly-crimson-turkey
      github.com/eosc-synergy/eosc-perf restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-linen-barracuda.sh
        container: qc.doc_grumpy-champagne-turtle
  QC.Lic:
    repos:
      github.com/eosc-synergy/eosc-perf licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-persimmon-gharial.sh
        container: qc.lic_pokey-peach-scorpion
  QC.Met:
    repos:
      github.com/eosc-synergy/eosc-perf validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-white-bordeaux.sh
        container: qc.met_bumpy-wheat-rat
  QC.Sec:
    repos:
      github.com/eosc-synergy/eosc-perf bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-russet-pinscher.sh
        container: qc.sec_boozy-cyan-moorhen
  QC.Sty:
    repos:
      github.com/eosc-synergy/eosc-perf flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-goldenrod-lemur.sh
        container: qc.sty_tacky-yellow-angora
      github.com/eosc-synergy/eosc-perf hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-russet-javanese.sh
        container: qc.sty_flimsy-tan-millipede
      github.com/eosc-synergy/eosc-perf jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-gold-neanderthal.sh
        container: qc.sty_greasy-eggplant-shrimp
  QC.Ver:
    repos:
      github.com/eosc-synergy/eosc-perf get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-ivory-tamarin.sh
        container: qc.ver_woozy-cornflower-meerkat
timeout: 5400
